### ISSUE TITLE
[UnitaryHack] Implementing state expectation in parallel for a given batch of stabilizer states

### ISSUE THREAD

**Issue by hongyehu** [hongyehu/PyClifford#15]
Given a batch of stabilizer states and a Pauli operator, one needs to implement the evaluation of their expectation values in parallel. One potential solution is vectorization like torchclifford.

**Comment by lavanya-m-k** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by hongyehu** [comment]
@lavanya-m-k please go ahead, I am looking forward to seeing your PR!
 :)

**Comment by teng10** [comment]
Hey @lavanya-m-k , I just saw your comment now, I want to let you know that I have also been working on this issue.
How's it going for you? Let me know if you want to work together on it!
Yan

**Comment by hongyehu** [comment]
This issue is closed, and @teng10 's PR has been merged.

**Comment by natestemen** [comment]
@hongyehu please assign the hacker who should receive the bounty (looks like @teng10 in this case) so our system can ensure they receive payment.

**Comment by hongyehu** [comment]
Hi @natestemen, @teng10 should receive the bounty for this issue. Thanks!

**Comment by natestemen** [comment]
@hongyehu is it possible to assign Yanting? The bounty will then show up on our website under their alias.
