### ISSUE TITLE
[UnitaryHack] Benchmarking and profiling the speed of pyclifford and torchclifford

### ISSUE THREAD

**Issue by hongyehu** [hongyehu/PyClifford#17]
To close this issue, one needs to profile the speed of pyclifford, and torchclifford to point out the bottleneck for the speed and potentially solutions. Currently, all the underlying mathematical functions are implemented in `utils.py` file, and JIT compiled with Numba. 
Still, there is room for optimization. Successfully solution needs to be able to pinpoint the the bottleneck and provide potential solutions (a partial implementation and show the implementation will speed up pyclifford)

**Comment by lavanya-m-k** [comment]
I would like to work on this issue. Can you please assign this to me?
