### ISSUE TITLE
[unitaryHack] Intermediate representation of circuits and link to `stim` package for quantum error correction

### ISSUE THREAD

**Issue by hongyehu** [hongyehu/PyClifford#18]
To close this issue, one needs to design an intermediate representation of quantum circuit with pyclifford language. Users can use it to define quantum error correction code (repetition code, for example) and apply measurements and detectors (see `stim` for definition) for quantum error correction. Then this intermediate representation is transferred to `stim`'s language and be able to use `stim` as a backend for simulation.

**Comment by hongyehu** [comment]
@AbdullahKazi500 Thanks. This issue is assigned to you. Please let us know if you need any help on PyClifford on our side. We will provide more information on this hack question shortly today. Have fun hacking!

**Comment by s-aldaihan** [comment]
Interested in this issue if still open @hongyehu

**Comment by natestemen** [comment]
Hey everyone, just to clarify, commenting on an issue is to indicate you are interested! Until a PR has been merged by the maintainer (@hongyehu in this case), the bounty is still up for grabs! Anyone is welcome to work on the issue until it is closed.

**Comment by hongyehu** [comment]
Thanks for the clarification @natestemen. Then feel free to try to get PR merged @s-aldaihan @AbdullahKazi500 :)
